# fly.toml app configuration file generated for awe-vibes-server on 2025-03-21T18:53:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'awe-vibes-server'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 2567
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'on-failure'
  retries = 10
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
