# fly.toml app configuration file generated for awe-whackafluffle on 2025-03-19T22:16:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'awe-whackafluffle'
primary_region = 'iad'

[env]
GAME_ID = "RbwO8W68yc29ekZAJyrO"
SINGLE_ROOM = "true"

[build]

[http_service]
internal_port = 2567
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[restart]]
policy = 'on-failure'
retries = 10
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
